# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='preview/'),
        ),
    ]
